# Generated by Django 4.1.7 on 2023-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.BigIntegerField()),
                ('humidity', models.BigIntegerField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
