# Generated by Django 4.1.7 on 2023-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
