# Generated by Django 4.1.7 on 2023-05-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0009_alter_client_nodeuser'),
        ('supervisor_login', '0002_supervisor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='myclients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='add_user.client'),
        ),
    ]
