# Generated by Django 4.1.7 on 2023-05-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_login', '0003_supervisor_myclients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='myclients',
        ),
    ]
