# Generated by Django 4.1.7 on 2023-04-12 12:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
    ]
