# Generated by Django 4.1.7 on 2023-04-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superspace', '0004_remove_supervisor_position_nodes_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supervisor',
        ),
    ]
