# Generated by Django 4.1.7 on 2023-04-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superspace', '0005_delete_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nodes',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
