# Generated by Django 4.1.7 on 2023-04-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0002_user_nodeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='id',
        ),
        migrations.AddField(
            model_name='nodes',
            name='id_node',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
