# Generated by Django 4.1.7 on 2023-05-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0003_remove_nodes_id_nodes_id_node'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='client',
        ),
    ]
