# Generated by Django 4.1.7 on 2023-05-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0005_add_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_project',
            new_name='project',
        ),
    ]
