# Generated by Django 4.1.7 on 2023-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0006_rename_add_project_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_de_création',
        ),
        migrations.RemoveField(
            model_name='project',
            name='testtest',
        ),
        migrations.AddField(
            model_name='project',
            name='date_de_debut',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_de_fin',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
