# Generated by Django 4.1.7 on 2023-05-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0007_remove_project_date_de_création_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pays',
            new_name='region',
        ),
    ]
