# Generated by Django 4.1.7 on 2023-05-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor_login', '0004_remove_supervisor_myclients'),
        ('add_user', '0009_alter_client_nodeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='supervisor_login.supervisor'),
        ),
    ]
