# Generated by Django 4.1.7 on 2023-05-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0010_client_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='add_user.project'),
        ),
    ]
