# Generated by Django 4.1.7 on 2023-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0013_remove_client_project_project_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='id_projet',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
