# Generated by Django 4.1.7 on 2023-05-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_user', '0015_nodes_rssi_nodes_ref_alter_client_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='snr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
